In [8]:
import numpy as np

In [ ]:
#attributes of numpy
arr = np.array(((1, 2), (4, "Hello")))      # value, datatype 
print(arr)
print(arr.ndim)
print(arr.shape)
print(type(arr))
print(arr.dtype)

[['1' '2']
 ['4' 'Hello']]
2
(2, 2)
<class 'numpy.ndarray'>
<U21


In [ ]:
#methods of numpy
arr = np.array(((1, 2), (4, "Hello")))         # value, datatype # to create an array
# print(arr)

print(np.arange(3))                # start , stop , step
print(np.random.rand(1,2))         # size
print(np.random.randint(0,10,12))  # start , end , element


[0 1 2]
[[0.04272101 0.84951224]]
[5 6 2 4 5 6 1 3 7 0 8 6]


In [127]:
# create a guessing game where the user willenter a number and you have to tell number is big or small
# loop user will enter another number make it untill user guess the number 
# add num , subs num

import random

num = random.randint(1, 100)
count = 0

while True:
    guess = int(input("Guess a number (1-100): "))
    count += 1

    if guess > num:
        print("Number is big!")
    elif guess < num:
        print("Number is small!")
    else:
        print("Correct! You guessed it in", count, "attempts.")
        break


Number is big!
Number is small!
Correct! You guessed it in 3 attempts.


In [10]:
# zeros
print(np.zeros((3,4,2), dtype=int))

# ones
print(np.ones((3,4,2), dtype=int))


[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [19]:
import numpy as np
arr=np.random.randint(1,10,12)
print(arr)
print(arr.shape)
print(arr.reshape(3,4))
print(arr)




[3 7 4 2 2 9 6 2 1 1 2 4]
(12,)
[[3 7 4 2]
 [2 9 6 2]
 [1 1 2 4]]
[3 7 4 2 2 9 6 2 1 1 2 4]


In [20]:
arr+arr      #opt overloading

array([ 6, 14,  8,  4,  4, 18, 12,  4,  2,  2,  4,  8], dtype=int32)

In [21]:
list1 = [1, 2, 3, 4]
list1+list1

[1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
# max , min , argmax , argmin 
print(arr)
max(arr)
arr.max()     #np method
max(list1)    #python method

arr.min()
arr.argmax()
arr.argmin()
arr.mean()
arr.std()


[3 7 4 2 2 9 6 2 1 1 2 4]


np.float64(2.43099202430247)

In [27]:
arr[3]                          #indexing
arr[0:7:2]  #start:stop:step    #slicing

array([3, 4, 2, 6], dtype=int32)

In [28]:
np.flip(arr)   

array([4, 2, 1, 1, 2, 6, 9, 2, 2, 4, 7, 3], dtype=int32)

In [31]:
np.arange(1, 30, 2)

15

In [ ]:
arr.reshape(3, 4)

ValueError: cannot reshape array of size 1 into shape (5,)